var string = 'Isso é uma string';
console.log(string);
var numberString = '777';
console.log(typeof numberString);
var idade = 27;
var nome = 'Felps';
var sobrenome = 'Lms';
var nomeCompleto = nome + ' ' + sobrenome;
console.log(nomeCompleto);
var itsTime = "It's time";
console.log(itsTime);
console.log(typeof nome);